[package]
name = "nbody-simulation"
version = "0.1.0"
edition = "2024"

[dependencies]
nalgebra = "0.33"
rand = "0.8"
rayon = "1.7"

macroquad = "0.4"

[[bin]]
name = "nbody-simulation"
path = "src/main.rs"
